"use client";

import { useRouter } from "next/navigation";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../ui/card";
import { Users, UserCircle, BookOpen, DollarSign, Megaphone } from "lucide-react";

export function AdminDashboard() {
  const router = useRouter();
  return (
    <div className="space-y-6">
      <div><h2 className="text-3xl font-bold">Admin Dashboard</h2><p className="text-gray-600">Manage school operations and monitor performance</p></div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <Card><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-sm font-medium">Total Students</CardTitle><Users className="w-4 h-4 text-blue-600" /></CardHeader><CardContent><div className="text-2xl font-bold">2,543</div><p className="text-xs text-gray-600 mt-2">+12% from last year</p></CardContent></Card>
        <Card><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-sm font-medium">Total Teachers</CardTitle><UserCircle className="w-4 h-4 text-green-600" /></CardHeader><CardContent><div className="text-2xl font-bold">152</div><p className="text-xs text-gray-600 mt-2">+5 new this semester</p></CardContent></Card>
        <Card><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-sm font-medium">Active Classes</CardTitle><BookOpen className="w-4 h-4 text-orange-600" /></CardHeader><CardContent><div className="text-2xl font-bold">85</div><p className="text-xs text-gray-600 mt-2">Across all grades</p></CardContent></Card>
        <Card><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-sm font-medium">Revenue (Monthly)</CardTitle><DollarSign className="w-4 h-4 text-purple-600" /></CardHeader><CardContent><div className="text-2xl font-bold">INR 42.5L</div><p className="text-xs text-gray-600 mt-2">Fee collection</p></CardContent></Card>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card className="lg:col-span-2"><CardHeader><CardTitle>Recent Activity</CardTitle><CardDescription>Latest system activities and updates</CardDescription></CardHeader><CardContent><div className="space-y-4">{[{ action: "New student enrolled", detail: "Aarav Sharma - Class 10-A", time: "2 hours ago", type: "student" }, { action: "Grade submission", detail: "Dr. Priya Mehta - Mathematics", time: "4 hours ago", type: "grade" }, { action: "Fee payment received", detail: "Diya Patel - Q2 2026", time: "5 hours ago", type: "payment" }, { action: "New announcement posted", detail: "Annual Sports Day", time: "1 day ago", type: "announcement" }, { action: "Teacher added", detail: "Mr. Rohan Kumar - Science", time: "2 days ago", type: "teacher" }].map((activity, index) => <div key={index} className="flex items-start gap-4 p-3 bg-gray-50 rounded-lg"><div className={`w-2 h-2 mt-2 rounded-full ${activity.type === "student" ? "bg-blue-500" : activity.type === "grade" ? "bg-green-500" : activity.type === "payment" ? "bg-purple-500" : activity.type === "announcement" ? "bg-orange-500" : "bg-gray-500"}`} /><div className="flex-1"><p className="font-medium">{activity.action}</p><p className="text-sm text-gray-600">{activity.detail}</p><p className="text-xs text-gray-500 mt-1">{activity.time}</p></div></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Quick Actions</CardTitle><CardDescription>Common administrative tasks</CardDescription></CardHeader><CardContent><div className="space-y-3"><button onClick={() => router.push("/admin/students")} className="w-full p-4 border rounded-lg hover:shadow-md transition-shadow text-left"><Users className="w-6 h-6 text-blue-600 mb-2" /><h4 className="font-semibold">Manage Students</h4><p className="text-sm text-gray-600">Add, edit, or remove students</p></button><button onClick={() => router.push("/admin/teachers")} className="w-full p-4 border rounded-lg hover:shadow-md transition-shadow text-left"><UserCircle className="w-6 h-6 text-green-600 mb-2" /><h4 className="font-semibold">Manage Teachers</h4><p className="text-sm text-gray-600">View and manage faculty</p></button><button onClick={() => router.push("/admin/announcements")} className="w-full p-4 border rounded-lg hover:shadow-md transition-shadow text-left"><Megaphone className="w-6 h-6 text-orange-600 mb-2" /><h4 className="font-semibold">Create Announcement</h4><p className="text-sm text-gray-600">Post school-wide updates</p></button></div></CardContent></Card></div>
    </div>
  );
}
