"use client";
import { useMemo, useState } from "react";
import { BellRing, Megaphone, Receipt, Search, ShieldCheck, Sparkles, TrendingUp, Users } from "lucide-react";
import { createAnnouncement, createBanner, createLeave, createResult, createUser, markAttendance, reviewLeave, updateUserStatus } from "../../services/api";
import { DashboardPayload, LeaveRecord, Role } from "../../services/types";

const views: Record<Role, string[]> = {
  student: ["Overview", "Attendance", "Results", "Fees"],
  teacher: ["Overview", "Classes", "Attendance", "Grades"],
  hr: ["Overview"],
  admission: ["Overview"],
  admin: ["Overview", "Students", "Teachers", "Announcements"]
};
const firstView: Record<Role, string> = { student: "Overview", teacher: "Overview", hr: "Overview", admission: "Overview", admin: "Overview" };
const badge = (value: string) => value === "approved" || value === "active" || value === "paid" ? "bg-emerald-50 text-emerald-700" : value === "pending" || value === "partial" ? "bg-amber-50 text-amber-700" : "bg-rose-50 text-rose-700";

function Header({ kicker, title, copy }: { kicker: string; title: string; copy: string }) {
  return <div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">{kicker}</p><h3 className="mt-2 text-2xl font-semibold">{title}</h3><p className="mt-2 text-sm text-slate-600">{copy}</p></div>;
}
function Metrics({ items }: { items: Array<{ label: string; value: string | number; tone?: string }> }) {
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{items.map((item) => <div key={item.label} className="metric-card"><p className="text-sm text-slate-500">{item.label}</p><p className={`mt-2 text-3xl font-semibold ${item.tone ?? "text-slate-950"}`}>{item.value}</p></div>)}</div>;
}

export function RoleDashboardSchool({ token, payload, onRefresh }: { token: string; payload: DashboardPayload; onRefresh: () => Promise<void> }) {
  const { user } = payload;
  const [active, setActive] = useState(firstView[user.role]);
  const [busy, setBusy] = useState("");
  const [message, setMessage] = useState("");
  const [search, setSearch] = useState("");
  const students = payload.roleCollections.students;
  const teachers = payload.roleCollections.teachers;
  const leaves = payload.leaves.filter((item) => item.status === "pending");
  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return payload.users;
    return payload.users.filter((item) => item.name.toLowerCase().includes(q) || item.email.toLowerCase().includes(q) || item.department.toLowerCase().includes(q));
  }, [payload.users, search]);
  async function act(key: string, work: () => Promise<unknown>, text: string) {
    try { setBusy(key); setMessage(""); await work(); await onRefresh(); setMessage(text); } catch (e) { setMessage(e instanceof Error ? e.message : "Action failed."); } finally { setBusy(""); }
  }

  let body = <div className="space-y-6"><Metrics items={[{ label: "Students", value: payload.stats.totalStudents, tone: "text-[var(--brand)]" }, { label: "Teachers", value: payload.stats.totalTeachers }, { label: "Open requests", value: payload.stats.openLeaves, tone: "text-[var(--accent)]" }, { label: "Avg attendance", value: `${payload.stats.averageAttendance}%`, tone: "text-emerald-700" }]} /><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="card-surface p-6"><Header kicker="Updates" title="Live school feed" copy="Role-filtered notifications and announcements." /><div className="mt-5 space-y-3">{payload.notifications.map((item) => <div key={item.id} className="rounded-2xl border border-black/5 bg-stone-50 p-4"><div className="flex items-start gap-3"><BellRing className="mt-1 h-4 w-4 text-[var(--brand)]" /><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.body}</p></div></div></div>)}</div></div><div className="space-y-6"><div className="card-surface p-6"><Header kicker="Pulse" title="Snapshot" copy="Fast operational summary." /><div className="mt-5 space-y-3"><div className="rounded-2xl bg-stone-50 p-4"><p className="text-sm text-slate-500">Active banners</p><p className="mt-2 text-3xl font-semibold">{payload.stats.activeBanners}</p></div><div className="rounded-2xl bg-stone-50 p-4"><p className="text-sm text-slate-500">Visible announcements</p><p className="mt-2 text-3xl font-semibold">{payload.announcements.length}</p></div></div></div><div className="card-surface p-6"><div className="flex items-center gap-3"><Sparkles className="h-5 w-5 text-[var(--accent)]" /><h3 className="text-xl font-semibold">Backend wired</h3></div><p className="mt-3 text-sm text-slate-600">These screens use the real auth, content, leave, result, attendance, and user APIs.</p></div></div></div></div>;

  if (user.role === "student" && active === "Attendance") body = <div className="space-y-6"><Metrics items={payload.attendance.map((item) => ({ label: item.subject, value: `${item.percentage}%`, tone: item.percentage >= 90 ? "text-emerald-700" : "text-[var(--accent)]" }))} /><div className="card-surface p-6"><Header kicker="Attendance" title="Subject record" copy="Live data from the backend." /><div className="mt-5 grid gap-4 md:grid-cols-2">{payload.attendance.map((item) => <div key={item.id} className="rounded-2xl border border-black/5 bg-stone-50 p-5"><div className="flex items-center justify-between"><p className="text-lg font-semibold">{item.subject}</p><span className={`rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-[0.16em] ${badge(item.percentage >= 90 ? "approved" : "pending")}`}>{item.percentage >= 90 ? "good" : "watch"}</span></div><p className="mt-3 text-sm text-slate-600">Present {item.present} out of {item.classesHeld} classes.</p></div>)}</div></div></div>;
  if (user.role === "student" && active === "Results") body = <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="card-surface p-6"><Header kicker="Results" title="Academic performance" copy="Loaded from the results API." /><div className="mt-5 space-y-4">{payload.results.map((result) => <div key={result.id} className="rounded-2xl border border-black/5 bg-stone-50 p-5"><div className="flex items-center justify-between"><p className="text-lg font-semibold">{result.semester}</p><p className="text-sm font-medium text-slate-500">GPA {result.gpa}</p></div><div className="mt-4 grid gap-3 md:grid-cols-2">{result.subjects.map((subject) => <div key={subject.name} className="rounded-2xl bg-white p-4"><p className="font-semibold">{subject.name}</p><p className="mt-1 text-sm text-slate-600">{subject.marks} marks</p></div>)}</div></div>)}</div></div><form className="card-surface space-y-4 p-6" onSubmit={async (e) => { e.preventDefault(); await act("student-leave", async () => createLeave(token, { type: "medical", from: "2026-04-22", to: "2026-04-23", reason: "Medical rest" }), "Leave request submitted."); }}><Header kicker="Action" title="Apply for leave" copy="This writes into the backend leave flow." /><button disabled={busy === "student-leave"} className="rounded-full bg-[var(--brand)] px-5 py-3 font-semibold text-white disabled:opacity-60">{busy === "student-leave" ? "Submitting..." : "Submit leave request"}</button></form></div>;
  if (user.role === "student" && active === "Fees") body = <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="card-surface p-6"><Header kicker="Fees" title="Payment status" copy="Current fee record from the backend." />{payload.fees ? <div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-stone-50 p-5"><p className="text-sm text-slate-500">Total fee</p><p className="mt-2 text-3xl font-semibold">{payload.fees.total}</p></div><div className="rounded-2xl bg-stone-50 p-5"><p className="text-sm text-slate-500">Paid</p><p className="mt-2 text-3xl font-semibold text-emerald-700">{payload.fees.paid}</p></div><div className="rounded-2xl bg-stone-50 p-5"><p className="text-sm text-slate-500">Balance</p><p className="mt-2 text-3xl font-semibold text-[var(--accent)]">{payload.fees.total - payload.fees.paid}</p></div></div> : null}</div><div className="card-surface p-6"><div className="flex items-center gap-3"><Receipt className="h-5 w-5 text-[var(--brand)]" /><h3 className="text-xl font-semibold">Status</h3></div><div className="mt-4">{payload.fees ? <span className={`rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-[0.16em] ${badge(payload.fees.status)}`}>{payload.fees.status}</span> : null}</div><p className="mt-4 text-sm text-slate-600">Due date: {payload.fees?.dueDate ?? "n/a"}</p></div></div>;

  if (user.role === "teacher" && active === "Classes") body = <div className="card-surface p-6"><Header kicker="Classes" title="Student directory" copy="Teacher view mapped onto live portal data." /><div className="mt-5 grid gap-4 md:grid-cols-2">{students.map((item) => <div key={item.id} className="rounded-2xl border border-black/5 bg-stone-50 p-5"><p className="text-lg font-semibold">{item.name}</p><p className="mt-1 text-sm text-slate-600">{item.department}</p><p className="mt-3 text-sm text-slate-500">{item.email}</p></div>)}</div></div>;
  if (user.role === "teacher" && active === "Attendance") body = <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="card-surface p-6"><Header kicker="Attendance" title="Mark attendance" copy="This writes to the real attendance endpoint." />{students[0] ? <button disabled={busy === "teacher-attendance"} className="mt-5 rounded-full bg-[var(--brand)] px-5 py-3 font-semibold text-white disabled:opacity-60" onClick={() => act("teacher-attendance", async () => markAttendance(token, { studentId: students[0]!.id, subject: "Mathematics", classesHeld: 32, present: 30 }), `Attendance record saved for ${students[0]!.name}.`)}>{busy === "teacher-attendance" ? "Saving..." : `Mark ${students[0]!.name}`}</button> : null}</div><div className="card-surface p-6"><Header kicker="Approvals" title="Pending leave requests" copy="Approve from the teacher panel." /><div className="mt-5 space-y-3">{leaves.map((leave: LeaveRecord) => <div key={leave.id} className="rounded-2xl bg-stone-50 p-4"><div className="flex items-center justify-between gap-3"><p className="font-semibold capitalize">{leave.type} leave</p><span className={`rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-[0.16em] ${badge(leave.status)}`}>{leave.status}</span></div><p className="mt-2 text-sm text-slate-600">{leave.reason}</p><button disabled={busy === leave.id} className="mt-3 rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60" onClick={() => act(leave.id, async () => reviewLeave(token, leave.id, { status: "approved", note: "Reviewed by class teacher" }), "Leave approved.")}>{busy === leave.id ? "Approving..." : "Approve"}</button></div>)}</div></div></div>;
  if (user.role === "teacher" && active === "Grades") body = <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="card-surface p-6"><Header kicker="Grades" title="Publish result" copy="This uses the backend result creation route." />{students[0] ? <button disabled={busy === "teacher-grades"} className="mt-5 rounded-full bg-[var(--brand)] px-5 py-3 font-semibold text-white disabled:opacity-60" onClick={() => act("teacher-grades", async () => createResult(token, { studentId: students[0]!.id, semester: "Term 2", gpa: 9.1, subjects: [{ name: "Mathematics", marks: 92, grade: "A+" }, { name: "Science", marks: 88, grade: "A" }] }), `Result uploaded for ${students[0]!.name}.`)}>{busy === "teacher-grades" ? "Uploading..." : "Upload marks"}</button> : null}</div><div className="card-surface p-6"><div className="flex items-center gap-3"><TrendingUp className="h-5 w-5 text-[var(--accent)]" /><h3 className="text-xl font-semibold">Teaching summary</h3></div><p className="mt-4 text-sm text-slate-600">Attendance, approvals, and marks now stay in one workspace.</p></div></div>;

  if (user.role === "admin" && active === "Students") body = <div className="card-surface p-6"><Header kicker="Students" title="Student management" copy="Your admin student screen with real status updates." /><div className="mt-4 flex items-center gap-3 rounded-2xl border border-black/5 bg-stone-50 px-4 py-3"><Search className="h-4 w-4 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search students by name, email, or class" className="w-full bg-transparent text-sm outline-none" /></div><div className="mt-5 grid gap-3">{filtered.filter((item) => item.role === "student").map((item) => <div key={item.id} className="flex items-center justify-between rounded-2xl border border-black/5 bg-stone-50 p-4"><div><p className="font-semibold">{item.name}</p><p className="text-sm text-slate-500">{item.department} - {item.status}</p></div><button disabled={busy === item.id} className="rounded-full border border-black/10 px-4 py-2 text-sm disabled:opacity-60" onClick={() => act(item.id, async () => updateUserStatus(token, item.id, item.status === "active" ? "blocked" : "active"), `${item.name} status updated.`)}>{busy === item.id ? "Saving..." : item.status === "active" ? "Block" : "Unblock"}</button></div>)}</div></div>;
  if (user.role === "admin" && active === "Teachers") body = <div className="card-surface p-6"><Header kicker="Teachers" title="Faculty directory" copy="Teacher records from the backend user collection." /><div className="mt-5 grid gap-3 md:grid-cols-2">{teachers.map((item) => <div key={item.id} className="rounded-2xl border border-black/5 bg-stone-50 p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-lg font-semibold">{item.name}</p><p className="mt-1 text-sm text-slate-600">{item.designation}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-[0.16em] ${badge(item.status)}`}>{item.status}</span></div><p className="mt-3 text-sm text-slate-500">{item.email}</p></div>)}</div></div>;
  if (user.role === "admin" && active === "Announcements") body = <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(0,0.8fr)]"><div className="space-y-6"><form className="card-surface space-y-4 p-6" onSubmit={async (e) => { e.preventDefault(); await act("admin-announcement", async () => createAnnouncement(token, { title: "School circular", body: "Parent-teacher meeting schedule has been updated.", audience: ["all"] }), "Announcement published."); }}><Header kicker="Content" title="Publish announcement" copy="Writes to the real content API." /><button disabled={busy === "admin-announcement"} className="rounded-full bg-slate-950 px-5 py-3 font-semibold text-white disabled:opacity-60">{busy === "admin-announcement" ? "Publishing..." : "Publish announcement"}</button></form><div className="card-surface p-6"><Header kicker="Feed" title="Current announcements" copy="Recent school communication." /><div className="mt-5 space-y-3">{payload.announcements.map((item) => <div key={item.id} className="rounded-2xl bg-stone-50 p-4"><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.body}</p></div>)}</div></div></div><div className="space-y-6"><form className="card-surface space-y-4 p-6" onSubmit={async (e) => { e.preventDefault(); await act("admin-banner", async () => createBanner(token, { title: "School achievement banner", subtitle: "Annual day, Olympiad, and sports week updates are now live.", active: true }), "Banner created."); }}><Header kicker="Homepage" title="Create flash banner" copy="Banners feed directly into public content." /><button disabled={busy === "admin-banner"} className="rounded-full bg-[var(--brand)] px-5 py-3 font-semibold text-white disabled:opacity-60">{busy === "admin-banner" ? "Creating..." : "Create banner"}</button></form><div className="card-surface p-6"><Header kicker="Banners" title="Homepage rotator" copy="Current banner records." /><div className="mt-5 space-y-3">{payload.banners.map((item) => <div key={item.id} className="rounded-2xl bg-stone-50 p-4"><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.subtitle}</p></div>)}</div></div></div></div>;

  if (user.role === "hr") body = <div className="grid gap-6 lg:grid-cols-2"><form className="card-surface space-y-4 p-6" onSubmit={async (e) => { e.preventDefault(); await act("hr-create", async () => createUser(token, { role: "teacher", name: "Faculty Hire", email: `teacher${Date.now()}@lotusvalley.test`, department: "Middle School", designation: "Class Teacher", employeeOrStudentId: `LVS-EMP-${Date.now()}` }), "Teacher profile created."); }}><Header kicker="HR" title="Add teacher" copy="Creates staff profiles through the backend user route." /><button disabled={busy === "hr-create"} className="rounded-full bg-[var(--brand)] px-5 py-3 font-semibold text-white disabled:opacity-60">{busy === "hr-create" ? "Creating..." : "Create teacher profile"}</button></form><div className="card-surface p-6"><Header kicker="People Ops" title="Block and unblock staff" copy="Status changes are applied through the backend." /><div className="mt-4 space-y-3">{payload.users.filter((item) => item.role === "teacher" || item.role === "hr" || item.role === "admission").map((item) => <div key={item.id} className="flex items-center justify-between rounded-2xl bg-stone-50 p-4"><div><p className="font-semibold">{item.name}</p><p className="text-sm text-slate-500">{item.role} - {item.status}</p></div><button disabled={busy === item.id} className="rounded-full border border-black/10 px-4 py-2 text-sm disabled:opacity-60" onClick={() => act(item.id, async () => updateUserStatus(token, item.id, item.status === "active" ? "blocked" : "active"), `${item.name} status updated.`)}>{busy === item.id ? "Saving..." : item.status === "active" ? "Block" : "Unblock"}</button></div>)}</div></div></div>;
  if (user.role === "admission") body = <div className="grid gap-6 lg:grid-cols-2"><form className="card-surface space-y-4 p-6" onSubmit={async (e) => { e.preventDefault(); await act("admission-create", async () => createUser(token, { role: "student", name: "New Student", email: `student${Date.now()}@lotusvalley.test`, department: "Grade 8 - A", designation: "Student", employeeOrStudentId: `LVS-STU-${Date.now()}` }), "Student admission record created."); }}><Header kicker="Admissions" title="Create student record" copy="New entries are written into the backend user store." /><button disabled={busy === "admission-create"} className="rounded-full bg-[var(--brand)] px-5 py-3 font-semibold text-white disabled:opacity-60">{busy === "admission-create" ? "Creating..." : "Create student record"}</button></form><div className="card-surface p-6"><Header kicker="Enrollments" title="Recent student records" copy="Freshly added students appear after refresh." /><div className="mt-4 space-y-3">{students.map((item) => <div key={item.id} className="rounded-2xl bg-stone-50 p-4"><p className="font-semibold">{item.name}</p><p className="text-sm text-slate-500">{item.department} - {item.profile.employeeOrStudentId}</p></div>)}</div></div></div>;

  return <div className="space-y-6"><div className="card-surface p-3"><div className="flex flex-wrap gap-2">{views[user.role].map((item) => <button key={item} onClick={() => setActive(item)} className={`rounded-full px-4 py-2 text-sm font-medium transition ${item === active ? "bg-slate-950 text-white" : "bg-stone-100 text-slate-700 hover:bg-stone-200"}`}>{item}</button>)}</div></div>{body}{message ? <div className="card-surface px-5 py-4 text-sm font-medium text-emerald-700">{message}</div> : null}</div>;
}

